[[inputs.mock]]
  alias = "cluster heartbeat"
  metric_name = "cluster"
  interval = '${CLUSTER_HEARTBEAT_INTERVAL}'
  log_level = "error"
  [inputs.mock.tags]
    instance = '${LOCAL_NAME}'
    heartbeat = "true"
  [[inputs.mock.step]]
    name = "value"
    start = 0.0
    step = 1.0

[[inputs.influxdb_v2_listener]]
  alias = "cluster influxdb_v2_listener"
  service_address = ':${LOCAL_CLUSTER_PORT}'
  token = '${CLUSTER_TOKEN}'
  parser_type = "upstream"
  log_level = "error"
  [inputs.influxdb_v2_listener.tags]
    internal_CLUSTER_received = "x"

[[outputs.influxdb_v2]]
  alias = 'local output: ${LOCAL_NAME}'
  urls = ['http://127.0.0.1:${LOCAL_CLUSTER_PORT}']
  token = '${CLUSTER_TOKEN}'
  organization = ""
  bucket = ""
  content_encoding = "gzip"
  log_level = "error"
  flush_interval = '${CLUSTER_HEARTBEAT_INTERVAL}'
  metric_buffer_limit = 1
  [outputs.influxdb_v2.tagpass]
    heartbeat = ["*"]

[[outputs.influxdb_v2]]
  alias = 'remote output: ${REMOTE_1_NAME}'
  urls = ['http://${REMOTE_1_CLUSTER_HOST}:${REMOTE_1_CLUSTER_PORT}']
  token = '${CLUSTER_TOKEN}'
  organization = ""
  bucket = ""
  content_encoding = "gzip"
  log_level = "error"
  flush_interval = '${CLUSTER_HEARTBEAT_INTERVAL}'
  metric_buffer_limit = 1
  [outputs.influxdb_v2.tagpass]
    heartbeat = ["*"]

[[outputs.influxdb_v2]]
  alias = 'remote output: ${REMOTE_2_NAME}'
  urls = ['http://${REMOTE_2_CLUSTER_HOST}:${REMOTE_2_CLUSTER_PORT}']
  token = '${CLUSTER_TOKEN}'
  organization = ""
  bucket = ""
  content_encoding = "gzip"
  log_level = "error"
  flush_interval = '${CLUSTER_HEARTBEAT_INTERVAL}'
  metric_buffer_limit = 1
  [outputs.influxdb_v2.tagpass]
    heartbeat = ["*"]

[[processors.starlark]]
  order = 1
  alias = "CLUSTER"
  script = "starlark.cluster.star"
  log_level = "debug"
  [processors.starlark.constants]
    const_local_instance_name = '${LOCAL_NAME}'
    const_configured_partners = '${LOCAL_NAME},${REMOTE_1_NAME},${REMOTE_2_NAME}'
    const_cluster_instance_name_tag = "instance"
    const_cluster_received_tag = "internal_CLUSTER_received"
    const_cluster_heartbeat_tag = "heartbeat"
    const_cluster_active_timeout = "5s"
    const_cluster_online_threshold = "5s"
    const_hagroups_tag = "internal_ha_group"
    const_hagroups = '''{
      "Prio_Telegraf_1": "telegraf_1:10,telegraf_2:5",
      "Prio_Telegraf_2": "telegraf_1:5,telegraf_2:10"
    }'''
